# render.yaml - Configuración de Render para SAM Metrología
# https://render.com/docs/blueprint-spec

services:
  # Servicio Web Principal
  - type: web
    name: sam-metrologia
    runtime: python
    plan: free  # Puedes cambiar a: starter, standard, pro
    region: oregon  # Región más cercana: ohio, oregon, frankfurt, singapore

    buildCommand: "./build.sh"
    startCommand: "./start.sh"

    # Archivos a incluir en el build
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9

      - key: SECRET_KEY
        generateValue: true

      - key: DATABASE_URL
        fromDatabase:
          name: sam-metrologia-db
          property: connectionString

      - key: AWS_ACCESS_KEY_ID
        sync: false  # Debes configurarlo manualmente en Render Dashboard

      - key: AWS_SECRET_ACCESS_KEY
        sync: false  # Debes configurarlo manualmente en Render Dashboard

      - key: AWS_STORAGE_BUCKET_NAME
        sync: false  # Debes configurarlo manualmente en Render Dashboard

      - key: AWS_S3_REGION_NAME
        value: us-east-2  # Cambia según tu región de S3

      - key: DEBUG_VALUE
        value: False

      - key: RENDER_EXTERNAL_HOSTNAME
        value: sam-9o6o.onrender.com  # Cambia por tu dominio de Render

      # Configuraciones opcionales de email
      - key: EMAIL_HOST
        value: smtp.gmail.com
        sync: false

      - key: EMAIL_PORT
        value: 587

      - key: EMAIL_HOST_USER
        sync: false  # Configurar manualmente

      - key: EMAIL_HOST_PASSWORD
        sync: false  # Configurar manualmente

      - key: ADMIN_EMAIL
        value: metrologiasam@gmail.com

    # Health check endpoint
    healthCheckPath: /

    # Auto-deploy desde GitHub
    autoDeploy: true

    # Configuración de disco persistente (opcional para logs)
    disk:
      name: sam-logs
      mountPath: /opt/render/project/src/logs
      sizeGB: 1

# Base de datos PostgreSQL
databases:
  - name: sam-metrologia-db
    databaseName: sam_db
    user: sam_user
    plan: free  # Puedes cambiar a: starter, standard, pro
    region: oregon  # Misma región que el servicio web
    ipAllowList: []  # Vacío = permite desde cualquier IP (Render managed)
