# Generated by Django 5.2.4 on 2025-08-16 05:45

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedimiento',
            name='empresa',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='procedimientos', to='core.empresa', verbose_name='Empresa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='procedimiento',
            name='documento_pdf',
            field=models.FileField(blank=True, null=True, upload_to=core.models.get_upload_path),
        ),
        migrations.AlterUniqueTogether(
            name='procedimiento',
            unique_together={('codigo', 'empresa')},
        ),
    ]
