# Generated by Django 5.2.4 on 2025-08-07 18:20

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibracion',
            name='intervalos_calibracion_pdf',
            field=models.FileField(blank=True, null=True, upload_to=core.models.get_upload_path, verbose_name='Intervalos de Calibración (PDF)'),
        ),
    ]
