# Generated by Django 5.2.4 on 2025-07-29 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='error_maximo_permisible',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Error Máximo Permisible'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ubicación'),
        ),
    ]
