# Generated by Django 5.2.4 on 2025-09-19 21:22
# Performance Optimization - Critical Database Indexes

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        # Índice compuesto para equipos por empresa y estado
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_equipo_empresa_estado ON core_equipo(empresa_id, estado);",
            reverse_sql="DROP INDEX IF EXISTS idx_equipo_empresa_estado;"
        ),

        # Índice para próximas actividades de calibración
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_equipo_proxima_calibracion ON core_equipo(proxima_calibracion) WHERE proxima_calibracion IS NOT NULL;",
            reverse_sql="DROP INDEX IF EXISTS idx_equipo_proxima_calibracion;"
        ),

        # Índice para próximos mantenimientos
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_equipo_proximo_mantenimiento ON core_equipo(proximo_mantenimiento) WHERE proximo_mantenimiento IS NOT NULL;",
            reverse_sql="DROP INDEX IF EXISTS idx_equipo_proximo_mantenimiento;"
        ),

        # Índice para próximas comprobaciones
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_equipo_proxima_comprobacion ON core_equipo(proxima_comprobacion) WHERE proxima_comprobacion IS NOT NULL;",
            reverse_sql="DROP INDEX IF EXISTS idx_equipo_proxima_comprobacion;"
        ),

        # Índice para fechas de calibración
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_calibracion_fecha ON core_calibracion(fecha_calibracion);",
            reverse_sql="DROP INDEX IF EXISTS idx_calibracion_fecha;"
        ),

        # Índice para fechas de mantenimiento
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_mantenimiento_fecha ON core_mantenimiento(fecha_mantenimiento);",
            reverse_sql="DROP INDEX IF EXISTS idx_mantenimiento_fecha;"
        ),

        # Índice para fechas de comprobación
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_comprobacion_fecha ON core_comprobacion(fecha_comprobacion);",
            reverse_sql="DROP INDEX IF EXISTS idx_comprobacion_fecha;"
        ),

        # Índice compuesto para actividades por equipo y fecha
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_calibracion_equipo_fecha ON core_calibracion(equipo_id, fecha_calibracion);",
            reverse_sql="DROP INDEX IF EXISTS idx_calibracion_equipo_fecha;"
        ),

        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_mantenimiento_equipo_fecha ON core_mantenimiento(equipo_id, fecha_mantenimiento);",
            reverse_sql="DROP INDEX IF EXISTS idx_mantenimiento_equipo_fecha;"
        ),

        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_comprobacion_equipo_fecha ON core_comprobacion(equipo_id, fecha_comprobacion);",
            reverse_sql="DROP INDEX IF EXISTS idx_comprobacion_equipo_fecha;"
        ),
    ]
