# Generated by Django 5.2.4 on 2025-08-19 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_procedimiento_empresa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanSuscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Plan')),
                ('limite_equipos', models.IntegerField(default=0, verbose_name='Límite de Equipos')),
                ('precio_mensual', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio Mensual')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción del Plan')),
                ('duracion_meses', models.IntegerField(default=0, help_text='Duración del plan en meses (0 para indefinido)', verbose_name='Duración (meses)')),
            ],
            options={
                'verbose_name': 'Plan de Suscripción',
                'verbose_name_plural': 'Planes de Suscripción',
                'ordering': ['precio_mensual'],
                'permissions': [('can_view_plansuscripcion', 'Can view plan suscripcion'), ('can_add_plansuscripcion', 'Can add plan suscripcion'), ('can_change_plansuscripcion', 'Can change plan suscripcion'), ('can_delete_plansuscripcion', 'Can delete plan suscripcion')],
            },
        ),
        migrations.AddField(
            model_name='empresa',
            name='acceso_manual_activo',
            field=models.BooleanField(default=False, verbose_name='Acceso Manual Activo'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='duracion_prueba_dias',
            field=models.IntegerField(default=30, verbose_name='Duración Prueba (días)'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='es_periodo_prueba',
            field=models.BooleanField(default=False, verbose_name='¿Es Período de Prueba?'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='estado_suscripcion',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Expirado', 'Expirado'), ('Cancelado', 'Cancelado')], default='Activo', max_length=50, verbose_name='Estado de Suscripción'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='fecha_inicio_plan',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Inicio Plan'),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='empresa',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='ubicaciones', to='core.empresa', verbose_name='Empresa'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='ubicacion',
            unique_together={('nombre', 'empresa')},
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo', models.CharField(max_length=255, verbose_name='Nombre del Archivo')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('archivo_s3_path', models.CharField(blank=True, max_length=500, null=True, verbose_name='Ruta en S3')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Subida')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos_generales', to='core.empresa', verbose_name='Empresa Asociada')),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Subido por')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-fecha_subida'],
                'permissions': [('can_view_documento', 'Can view documento'), ('can_add_documento', 'Can add documento'), ('can_change_documento', 'Can change documento'), ('can_delete_documento', 'Can delete documento')],
            },
        ),
        migrations.AddField(
            model_name='empresa',
            name='plan_actual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.plansuscripcion', verbose_name='Plan de Suscripción Actual'),
        ),
    ]
