# Generated by Django 5.2.4 on 2025-08-20 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_plansuscripcion_empresa_acceso_manual_activo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='plan_actual',
        ),
        migrations.AddField(
            model_name='empresa',
            name='duracion_suscripcion_meses',
            field=models.IntegerField(blank=True, default=12, null=True, verbose_name='Duración Suscripción (meses)'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='limite_equipos_empresa',
            field=models.IntegerField(default=5, verbose_name='Límite Máximo de Equipos'),
        ),
    ]
