# Generated by Django 5.2.4 on 2025-09-19 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_performance_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='limite_almacenamiento_mb',
            field=models.IntegerField(default=1024, help_text='Límite máximo de almacenamiento en megabytes para archivos de la empresa', verbose_name='Límite de Almacenamiento (MB)'),
        ),
    ]
