# Generated by Django 5.2.4 on 2025-08-21 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_empresa_plan_actual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='limite_equipos',
            field=models.IntegerField(blank=True, default=0, help_text='Número máximo de equipos que esta empresa puede registrar. 0 para ilimitado.', null=True),
        ),
    ]
