# Generated by Django 5.2.4 on 2025-08-21 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_empresa_limite_equipos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='limite_equipos',
        ),
    ]
