# Generated by Django 5.2.4 on 2025-09-20 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_force_create_cache_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZipRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'En Cola'), ('processing', 'Procesando'), ('completed', 'Completado'), ('failed', 'Error'), ('expired', 'Expirado')], default='pending', max_length=20, verbose_name='Estado')),
                ('position_in_queue', models.IntegerField(verbose_name='Posición en Cola')),
                ('parte_numero', models.IntegerField(default=1, verbose_name='Número de Parte')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Iniciado en')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completado en')),
                ('file_path', models.CharField(blank=True, max_length=500, null=True, verbose_name='Ruta del Archivo')),
                ('file_size', models.BigIntegerField(blank=True, null=True, verbose_name='Tamaño del Archivo (bytes)')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Mensaje de Error')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expira en')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa', verbose_name='Empresa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Solicitud de ZIP',
                'verbose_name_plural': 'Solicitudes de ZIP',
                'ordering': ['position_in_queue', 'created_at'],
                'indexes': [models.Index(fields=['status', 'position_in_queue'], name='core_zipreq_status_3d492e_idx'), models.Index(fields=['user', 'status'], name='core_zipreq_user_id_2f2464_idx'), models.Index(fields=['empresa', 'status'], name='core_zipreq_empresa_3ce527_idx')],
            },
        ),
    ]
