# Generated by Django 5.2.4 on 2025-08-23 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_empresa_limite_equipos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresa',
            options={'ordering': ['nombre'], 'permissions': [('can_view_empresas', 'Can view empresas'), ('can_add_empresas', 'Can add empresas'), ('can_change_empresas', 'Can change empresas'), ('can_delete_empresas', 'Can can delete empresas')], 'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
    ]
