# Generated by Django 5.2.4 on 2025-09-20 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_ziprequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='is_trial',
            field=models.BooleanField(default=True, verbose_name='En período de prueba'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='subscription_status',
            field=models.CharField(choices=[('trial', 'Período de Prueba'), ('active', 'Suscripción Activa'), ('expired', 'Expirado'), ('suspended', 'Suspendido')], default='trial', max_length=20, verbose_name='Estado de Suscripción'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='trial_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de expiración del trial'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='trial_notified',
            field=models.BooleanField(default=False, verbose_name='Notificado sobre expiración'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='duracion_prueba_dias',
            field=models.IntegerField(default=7, verbose_name='Duración Prueba (días)'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='es_periodo_prueba',
            field=models.BooleanField(default=False, verbose_name='¿Es Período de Prueba? (Deprecado)'),
        ),
    ]
