# Generated by Django 5.2.4 on 2025-08-23 18:03

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_empresa_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresa',
            options={'ordering': ['nombre'], 'permissions': [('can_view_empresas', 'Can view empresas'), ('can_add_empresas', 'Can add empresas'), ('can_change_empresas', 'Can change empresas'), ('can_delete_empresas', 'Can can delete empresas')], 'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
        migrations.AddField(
            model_name='documento',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to=core.models.get_upload_path, verbose_name='Archivo'),
        ),
    ]
