# Generated by Django 5.2.4 on 2025-09-20 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_empresa_is_trial_empresa_subscription_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='duracion_plan_meses',
            field=models.IntegerField(blank=True, null=True, verbose_name='Duración Plan Pagado (meses)'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='fecha_activacion_plan',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha Activación Plan Actual'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='plan_actual',
            field=models.CharField(choices=[('trial', 'Período de Prueba'), ('free', 'Plan Gratuito'), ('paid', 'Plan Pagado')], default='trial', max_length=20, verbose_name='Plan Actual'),
        ),
    ]
