# Generated by Django 5.2.4 on 2025-09-20 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_empresa_duracion_plan_meses_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='duracion_plan_meses',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='fecha_activacion_plan',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='plan_actual',
        ),
    ]
