# Generated by Django 5.2.4 on 2025-08-23 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_empresa_options_documento_archivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='archivo_s3_path',
        ),
    ]
