# Generated by Django 5.2.4 on 2025-08-26 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_documento_archivo_s3_path'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresa',
            options={'ordering': ['nombre'], 'permissions': [('can_view_empresas', 'Can view empresas'), ('can_add_empresas', 'Can add empresas'), ('can_change_empresas', 'Can change empresas'), ('can_delete_empresas', 'Can delete empresas')], 'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
        migrations.RemoveField(
            model_name='documento',
            name='archivo',
        ),
        migrations.AddField(
            model_name='documento',
            name='archivo_s3_path',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Ruta en S3'),
        ),
    ]
