# Generated by Django 5.2.4 on 2025-09-20 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_empresa_duracion_plan_meses_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='is_trial',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='subscription_status',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='trial_expires_at',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='trial_notified',
        ),
    ]
