# Generated by Django 5.2.4 on 2025-09-21 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_empresa_is_trial_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipo',
            options={'ordering': ['codigo_interno'], 'permissions': [('can_view_equipo', 'Can view equipo'), ('can_add_equipo', 'Can add equipo'), ('can_change_equipo', 'Can change equipo'), ('can_delete_equipo', 'Can delete equipo'), ('can_export_reports', 'Can export reports (PDF, Excel, ZIP)'), ('can_view_strategic_dashboard', 'Can view strategic management dashboard')], 'verbose_name': 'Equipo', 'verbose_name_plural': 'Equipos'},
        ),
    ]
