# Generated by Django 5.2.4 on 2025-09-22 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_equipo_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibracion',
            name='costo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo de Calibración'),
        ),
        migrations.AddField(
            model_name='comprobacion',
            name='costo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo de Comprobación'),
        ),
    ]
