# Generated by Django 5.2.4 on 2025-09-23 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_calibracion_costo_comprobacion_costo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipo',
            options={'ordering': ['codigo_interno'], 'permissions': [('can_view_equipo', 'Can view equipo'), ('can_add_equipo', 'Can add equipo'), ('can_change_equipo', 'Can change equipo'), ('can_delete_equipo', 'Can delete equipo'), ('can_export_reports', 'Can export reports (PDF, Excel, ZIP)')], 'verbose_name': 'Equipo', 'verbose_name_plural': 'Equipos'},
        ),
        migrations.RemoveField(
            model_name='calibracion',
            name='costo',
        ),
        migrations.RemoveField(
            model_name='comprobacion',
            name='costo',
        ),
        migrations.AlterField(
            model_name='empresa',
            name='limite_almacenamiento_mb',
            field=models.IntegerField(default=1024, help_text='Límite máximo de almacenamiento en megabytes para archivos de la empresa', verbose_name='Límite de Almacenamiento (MB)'),
        ),
    ]
