# Generated by Django 5.2.4 on 2025-09-23 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_empresa_is_trial_and_more'),
        ('core', '0014_alter_equipo_options_remove_calibracion_costo_and_more'),
    ]

    operations = [
    ]
