# Generated by Django 5.2.4
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_merge_20250923_0332'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('notification_type', models.CharField(
                    choices=[
                        ('calibration', 'Calibración'),
                        ('maintenance', 'Mantenimiento'),
                        ('system', 'Sistema'),
                        ('info', 'Información'),
                        ('warning', 'Advertencia'),
                        ('error', 'Error')
                    ],
                    default='info',
                    max_length=20,
                    verbose_name='Tipo'
                )),
                ('priority', models.CharField(
                    choices=[
                        ('low', 'Baja'),
                        ('medium', 'Media'),
                        ('high', 'Alta'),
                        ('critical', 'Crítica')
                    ],
                    default='medium',
                    max_length=10,
                    verbose_name='Prioridad'
                )),
                ('is_read', models.BooleanField(default=False, verbose_name='Leída')),
                ('is_global', models.BooleanField(default=False, verbose_name='Global')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expira el')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creada el')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Leída el')),
                ('user', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='notifications',
                    to=settings.AUTH_USER_MODEL,
                    verbose_name='Usuario'
                )),
                ('empresa', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='notifications',
                    to='core.empresa',
                    verbose_name='Empresa'
                )),
                ('equipo', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='notifications',
                    to='core.equipo',
                    verbose_name='Equipo'
                )),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='core_notifi_user_id_6a7f17_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['empresa', 'is_read'], name='core_notifi_empresa_40f94d_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['created_at'], name='core_notifi_created_55cb7c_idx'),
        ),
    ]