# Generated by Django 5.2.4 on 2025-09-23 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_notification_system'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='core_notifi_user_id_cb8f07_idx',
            old_name='core_notifi_user_id_6a7f17_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='core_notifi_empresa_a0e744_idx',
            old_name='core_notifi_empresa_40f94d_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='core_notifi_created_d0c445_idx',
            old_name='core_notifi_created_55cb7c_idx',
        ),
    ]
