# Generated by Django 5.2.4 on 2025-09-23 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_rename_core_notifi_user_id_6a7f17_idx_core_notifi_user_id_cb8f07_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_backend', models.CharField(default='django.core.mail.backends.smtp.EmailBackend', max_length=100, verbose_name='Backend de Email')),
                ('email_host', models.CharField(default='smtp.gmail.com', max_length=100, verbose_name='Servidor SMTP')),
                ('email_port', models.IntegerField(default=587, verbose_name='Puerto SMTP')),
                ('email_use_tls', models.BooleanField(default=True, verbose_name='Usar TLS')),
                ('email_use_ssl', models.BooleanField(default=False, verbose_name='Usar SSL')),
                ('email_host_user', models.EmailField(blank=True, max_length=254, verbose_name='Usuario SMTP')),
                ('email_host_password', models.CharField(blank=True, max_length=200, verbose_name='Contraseña SMTP')),
                ('default_from_email', models.EmailField(default='noreply@sammetrologia.com', max_length=254, verbose_name='Email de envío por defecto')),
                ('default_from_name', models.CharField(default='SAM Metrología', max_length=100, verbose_name='Nombre de envío por defecto')),
                ('admin_email', models.EmailField(blank=True, max_length=254, verbose_name='Email de administrador')),
                ('notification_emails', models.TextField(blank=True, help_text='Emails adicionales para notificaciones, separados por coma', verbose_name='Emails adicionales')),
                ('is_active', models.BooleanField(default=False, verbose_name='Email activo')),
                ('test_email_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Último email de prueba')),
                ('last_error', models.TextField(blank=True, verbose_name='Último error')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Configuración de Email',
                'verbose_name_plural': 'Configuraciones de Email',
            },
        ),
    ]
