# Generated by Django 5.2.4 on 2025-09-24 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_add_performance_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='can_access_dashboard_decisiones',
            field=models.BooleanField(default=True, help_text='Permite al usuario acceder al dashboard de decisiones'),
        ),
    ]
