# Generated by Django 5.2.4 on 2025-09-25 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_customuser_can_access_dashboard_decisiones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='duracion_prueba_dias',
            field=models.IntegerField(default=30, verbose_name='Duración Prueba (días)'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='es_periodo_prueba',
            field=models.BooleanField(default=True, verbose_name='¿Es Período de Prueba? (Deprecado)'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='limite_equipos_empresa',
            field=models.IntegerField(default=50, verbose_name='Límite Máximo de Equipos'),
        ),
    ]
