# Generated by Django 5.2.4 on 2025-09-26 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_trial_empresas'),
    ]

    operations = [
        migrations.AddField(
            model_name='ziprequest',
            name='current_step',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Paso Actual'),
        ),
        migrations.AddField(
            model_name='ziprequest',
            name='equipos_procesados',
            field=models.IntegerField(default=0, verbose_name='Equipos Procesados'),
        ),
        migrations.AddField(
            model_name='ziprequest',
            name='estimated_completion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Tiempo Estimado de Finalización'),
        ),
        migrations.AddField(
            model_name='ziprequest',
            name='progress_percentage',
            field=models.IntegerField(default=0, verbose_name='Progreso (%)'),
        ),
        migrations.AddField(
            model_name='ziprequest',
            name='total_equipos',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total de Equipos'),
        ),
    ]
