# Generated by Django 5.2.4 on 2025-09-26 18:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_ziprequest_current_step_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacionZip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('zip_ready', 'ZIP Listo'), ('zip_failed', 'ZIP Falló'), ('zip_expired', 'ZIP Expirado')], max_length=20, verbose_name='Tipo')),
                ('status', models.CharField(choices=[('unread', 'No Leída'), ('read', 'Leída'), ('dismissed', 'Descartada')], default='unread', max_length=20, verbose_name='Estado')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Leído en')),
            ],
            options={
                'verbose_name': 'Notificación ZIP',
                'verbose_name_plural': 'Notificaciones ZIP',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='ziprequest',
            name='core_zipreq_status_3d492e_idx',
        ),
        migrations.RemoveIndex(
            model_name='ziprequest',
            name='core_zipreq_user_id_2f2464_idx',
        ),
        migrations.RemoveIndex(
            model_name='ziprequest',
            name='core_zipreq_empresa_3ce527_idx',
        ),
        migrations.AddField(
            model_name='notificacionzip',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='notificacionzip',
            name='zip_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ziprequest', verbose_name='Solicitud ZIP'),
        ),
    ]
