# Generated by Django 5.2.4 on 2025-09-26 22:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_notificacionzip_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemscheduleconfig',
            name='config_data',
        ),
        migrations.RemoveField(
            model_name='systemscheduleconfig',
            name='config_name',
        ),
        migrations.RemoveField(
            model_name='systemscheduleconfig',
            name='created_by',
        ),
        migrations.AddField(
            model_name='systemscheduleconfig',
            name='backup_monthly_day',
            field=models.IntegerField(default=1, verbose_name='Día del mes backup'),
        ),
        migrations.AddField(
            model_name='systemscheduleconfig',
            name='backup_monthly_enabled',
            field=models.BooleanField(default=True, verbose_name='Backup mensual'),
        ),
        migrations.AddField(
            model_name='systemscheduleconfig',
            name='backup_monthly_include_files',
            field=models.BooleanField(default=False, verbose_name='Incluir archivos'),
        ),
        migrations.AddField(
            model_name='systemscheduleconfig',
            name='backup_monthly_time',
            field=models.TimeField(default='01:00', verbose_name='Hora backup'),
        ),
        migrations.AddField(
            model_name='systemscheduleconfig',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='systemscheduleconfig',
            name='maintenance_daily_enabled',
            field=models.BooleanField(default=False, verbose_name='Mantenimiento diario'),
        ),
        migrations.AddField(
            model_name='systemscheduleconfig',
            name='maintenance_daily_tasks',
            field=models.TextField(default='cache,logs', verbose_name='Tareas mantenimiento'),
        ),
        migrations.AddField(
            model_name='systemscheduleconfig',
            name='maintenance_daily_time',
            field=models.TimeField(default='03:00', verbose_name='Hora mantenimiento'),
        ),
        migrations.AddField(
            model_name='systemscheduleconfig',
            name='maintenance_weekly_day',
            field=models.CharField(choices=[('monday', 'Lunes'), ('tuesday', 'Martes'), ('wednesday', 'Miércoles'), ('thursday', 'Jueves'), ('friday', 'Viernes'), ('saturday', 'Sábado'), ('sunday', 'Domingo')], default='sunday', max_length=10, verbose_name='Día semanal'),
        ),
        migrations.AddField(
            model_name='systemscheduleconfig',
            name='maintenance_weekly_enabled',
            field=models.BooleanField(default=True, verbose_name='Mantenimiento semanal'),
        ),
        migrations.AddField(
            model_name='systemscheduleconfig',
            name='maintenance_weekly_tasks',
            field=models.TextField(default='all', verbose_name='Tareas semanales'),
        ),
        migrations.AddField(
            model_name='systemscheduleconfig',
            name='maintenance_weekly_time',
            field=models.TimeField(default='02:00', verbose_name='Hora semanal'),
        ),
        migrations.AddField(
            model_name='systemscheduleconfig',
            name='name',
            field=models.CharField(default='Default Schedule', max_length=100, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='systemscheduleconfig',
            name='notifications_daily_enabled',
            field=models.BooleanField(default=True, verbose_name='Notificaciones diarias'),
        ),
        migrations.AddField(
            model_name='systemscheduleconfig',
            name='notifications_daily_time',
            field=models.TimeField(default='08:00', verbose_name='Hora notificaciones'),
        ),
        migrations.AddField(
            model_name='systemscheduleconfig',
            name='notifications_daily_types',
            field=models.TextField(default='consolidated', verbose_name='Tipos notificaciones'),
        ),
        migrations.AddField(
            model_name='systemscheduleconfig',
            name='notifications_weekly_day',
            field=models.CharField(choices=[('monday', 'Lunes'), ('tuesday', 'Martes'), ('wednesday', 'Miércoles'), ('thursday', 'Jueves'), ('friday', 'Viernes'), ('saturday', 'Sábado'), ('sunday', 'Domingo')], default='monday', max_length=10, verbose_name='Día notif. semanal'),
        ),
        migrations.AddField(
            model_name='systemscheduleconfig',
            name='notifications_weekly_enabled',
            field=models.BooleanField(default=True, verbose_name='Notif. semanales'),
        ),
        migrations.AddField(
            model_name='systemscheduleconfig',
            name='notifications_weekly_time',
            field=models.TimeField(default='09:00', verbose_name='Hora notif. semanal'),
        ),
        migrations.AddField(
            model_name='systemscheduleconfig',
            name='notifications_weekly_types',
            field=models.TextField(default='weekly', verbose_name='Tipos notif. semanal'),
        ),
        migrations.AddField(
            model_name='systemscheduleconfig',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
