# Generated by Django 5.2.4 on 2025-09-26 22:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_systemscheduleconfig_config_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='delete_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Razón de eliminación'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empresas_eliminadas', to=settings.AUTH_USER_MODEL, verbose_name='Eliminada por'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Eliminada'),
        ),
    ]
