# Generated by Django 5.2.4 on 2025-09-28 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_empresa_delete_reason_empresa_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='numero_serie',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de Serie'),
        ),
    ]
