# Generated by Django 5.2.4 on 2025-09-29 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_equipo_numero_serie'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibracion',
            name='costo_calibracion',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Costo total de la calibración', max_digits=10, null=True, verbose_name='Costo de Calibración'),
        ),
        migrations.AddField(
            model_name='calibracion',
            name='tecnico_asignado_sam',
            field=models.CharField(blank=True, help_text='Técnico de SAM que supervisó la calibración', max_length=100, null=True, verbose_name='Técnico SAM Asignado'),
        ),
        migrations.AddField(
            model_name='calibracion',
            name='tiempo_empleado_horas',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Horas empleadas en la calibración', max_digits=5, null=True, verbose_name='Tiempo Empleado (Horas)'),
        ),
        migrations.AddField(
            model_name='comprobacion',
            name='costo_comprobacion',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Costo total de la comprobación', max_digits=10, null=True, verbose_name='Costo de Comprobación'),
        ),
        migrations.AddField(
            model_name='comprobacion',
            name='tecnico_asignado_sam',
            field=models.CharField(blank=True, help_text='Técnico de SAM que supervisó la comprobación', max_length=100, null=True, verbose_name='Técnico SAM Asignado'),
        ),
        migrations.AddField(
            model_name='comprobacion',
            name='tiempo_empleado_horas',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Horas empleadas en la comprobación', max_digits=5, null=True, verbose_name='Tiempo Empleado (Horas)'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_management_user',
            field=models.BooleanField(default=False, help_text='Permite al usuario acceder al Dashboard de Gerencia Ejecutiva con métricas financieras y de gestión', verbose_name='Usuario de Gerencia'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='fecha_inicio_contrato_sam',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Inicio Contrato SAM'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='nivel_servicio_sam',
            field=models.CharField(choices=[('Básico', 'Básico'), ('Estándar', 'Estándar'), ('Premium', 'Premium')], default='Estándar', max_length=50, verbose_name='Nivel de Servicio SAM'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='normas_aplicables',
            field=models.CharField(blank=True, help_text='Ej: ISO 17020, ISO 17025, ISO 9001', max_length=200, null=True, verbose_name='Normas Aplicables'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='tarifa_mensual_sam',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Tarifa mensual que paga este cliente a SAM por servicios metrológicos', max_digits=10, null=True, verbose_name='Tarifa Mensual SAM'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='tipo_organismo',
            field=models.CharField(choices=[('OI', 'Organismo de Inspección'), ('Laboratorio', 'Laboratorio de Ensayo'), ('Certificacion', 'Entidad de Certificación'), ('Industrial', 'Empresa Industrial'), ('Otro', 'Otro')], default='Industrial', max_length=50, verbose_name='Tipo de Organismo'),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='costo_sam_interno',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Costo interno de SAM para realizar este mantenimiento', max_digits=10, null=True, verbose_name='Costo SAM Interno'),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='tecnico_asignado_sam',
            field=models.CharField(blank=True, help_text='Técnico de SAM que supervisó el mantenimiento', max_length=100, null=True, verbose_name='Técnico SAM Asignado'),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='tiempo_empleado_horas',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Horas empleadas en el mantenimiento', max_digits=5, null=True, verbose_name='Tiempo Empleado (Horas)'),
        ),
    ]
