# Generated by Django 5.2.4 on 2025-09-29 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_calibracion_costo_calibracion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='rol_usuario',
            field=models.CharField(choices=[('TECNICO', 'Técnico - Solo operaciones básicas'), ('ADMINISTRADOR', 'Administrador - Gestión completa de empresa'), ('GERENCIA', 'Gerencia - Acceso a métricas financieras y dashboard ejecutivo')], default='TECNICO', help_text='Define el nivel de acceso y permisos del usuario en el sistema', max_length=20, verbose_name='Rol de Usuario'),
        ),
        migrations.CreateModel(
            name='MetricasEficienciaMetrologica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_calculo', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('periodo_analisis', models.CharField(choices=[('MENSUAL', 'Mensual'), ('TRIMESTRAL', 'Trimestral'), ('ANUAL', 'Anual')], default='ANUAL', max_length=50, verbose_name='Período de análisis')),
                ('cumplimiento_calibraciones', models.DecimalField(decimal_places=2, default=0.0, help_text='Porcentaje de calibraciones realizadas a tiempo', max_digits=5, verbose_name='Cumplimiento Calibraciones (%)')),
                ('cumplimiento_mantenimientos', models.DecimalField(decimal_places=2, default=0.0, help_text='Porcentaje de mantenimientos realizados a tiempo', max_digits=5, verbose_name='Cumplimiento Mantenimientos (%)')),
                ('cumplimiento_comprobaciones', models.DecimalField(decimal_places=2, default=0.0, help_text='Porcentaje de comprobaciones realizadas a tiempo', max_digits=5, verbose_name='Cumplimiento Comprobaciones (%)')),
                ('trazabilidad_documentacion', models.DecimalField(decimal_places=2, default=0.0, help_text='Porcentaje de equipos con documentación completa', max_digits=5, verbose_name='Trazabilidad Documentación (%)')),
                ('disponibilidad_equipos', models.DecimalField(decimal_places=2, default=0.0, help_text='Porcentaje de equipos operativos y disponibles', max_digits=5, verbose_name='Disponibilidad Equipos (%)')),
                ('tiempo_promedio_gestion', models.DecimalField(decimal_places=2, default=0.0, help_text='Tiempo promedio para resolver actividades metrológicas', max_digits=5, verbose_name='Tiempo Promedio Gestión (días)')),
                ('indice_conformidad', models.DecimalField(decimal_places=2, default=0.0, help_text='Porcentaje de actividades que cumplen especificaciones', max_digits=5, verbose_name='Índice de Conformidad (%)')),
                ('eficacia_procesos', models.DecimalField(decimal_places=2, default=0.0, help_text='Efectividad general de los procesos metrológicos', max_digits=5, verbose_name='Eficacia de Procesos (%)')),
                ('costo_promedio_por_equipo', models.DecimalField(decimal_places=2, default=0.0, help_text='Costo promedio anual por equipo gestionado', max_digits=10, verbose_name='Costo Promedio por Equipo')),
                ('retorno_inversion_metrologia', models.DecimalField(decimal_places=2, default=0.0, help_text='Retorno de inversión en servicios metrológicos', max_digits=5, verbose_name='ROI Metrología (%)')),
                ('puntuacion_eficiencia_general', models.DecimalField(decimal_places=2, default=0.0, help_text='Puntuación general de eficiencia metrológica (0-100)', max_digits=5, verbose_name='Puntuación General de Eficiencia')),
                ('estado_eficiencia', models.CharField(choices=[('EXCELENTE', 'Excelente (90-100%)'), ('BUENO', 'Bueno (75-89%)'), ('REGULAR', 'Regular (60-74%)'), ('DEFICIENTE', 'Deficiente (40-59%)'), ('CRITICO', 'Crítico (<40%)')], default='REGULAR', max_length=20, verbose_name='Estado de Eficiencia')),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones sobre la eficiencia metrológica', null=True, verbose_name='Observaciones')),
                ('recomendaciones', models.TextField(blank=True, help_text='Recomendaciones para mejorar la eficiencia', null=True, verbose_name='Recomendaciones')),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metricas_eficiencia', to='core.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Métricas de Eficiencia Metrológica',
                'verbose_name_plural': 'Métricas de Eficiencia Metrológica',
                'ordering': ['-fecha_calculo'],
            },
        ),
    ]
