# Generated by Django 5.2.4 on 2025-09-29 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_customuser_rol_usuario_metricaseficienciametrologica'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='fecha_proximo_pago',
            field=models.DateField(blank=True, help_text='Fecha esperada del próximo pago', null=True, verbose_name='Fecha Próximo Pago'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='fecha_ultimo_pago',
            field=models.DateField(blank=True, help_text='Fecha en que se recibió el último pago', null=True, verbose_name='Fecha Último Pago'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='modalidad_pago',
            field=models.CharField(choices=[('MENSUAL', 'Pago Mensual'), ('TRIMESTRAL', 'Pago Trimestral (3 meses)'), ('SEMESTRAL', 'Pago Semestral (6 meses)'), ('ANUAL', 'Pago Anual (12 meses)')], default='MENSUAL', help_text='Modalidad de pago acordada con el cliente', max_length=20, verbose_name='Modalidad de Pago'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='valor_pago_acordado',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor total del pago según la modalidad (ej: $6000 si es semestral)', max_digits=10, null=True, verbose_name='Valor de Pago Acordado'),
        ),
    ]
