# Generated by Django 5.2.4 on 2025-09-29 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_empresa_fecha_proximo_pago_empresa_fecha_ultimo_pago_and_more'),
    ]

    operations = [
    ]
