# Generated by Django 5.2.4 on 2025-10-02 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20250929_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calibracion',
            name='tecnico_asignado_sam',
            field=models.CharField(blank=True, help_text='Técnico que supervisó la calibración', max_length=100, null=True, verbose_name='Técnico Asignado'),
        ),
        migrations.AlterField(
            model_name='comprobacion',
            name='tecnico_asignado_sam',
            field=models.CharField(blank=True, help_text='Técnico que supervisó la comprobación', max_length=100, null=True, verbose_name='Técnico Asignado'),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='costo_sam_interno',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Costo interno para realizar este mantenimiento', max_digits=10, null=True, verbose_name='Costo Interno'),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='tecnico_asignado_sam',
            field=models.CharField(blank=True, help_text='Técnico que supervisó el mantenimiento', max_length=100, null=True, verbose_name='Técnico Asignado'),
        ),
        migrations.CreateModel(
            name='NotificacionVencimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_actividad', models.CharField(choices=[('calibracion', 'Calibración'), ('mantenimiento', 'Mantenimiento'), ('comprobacion', 'Comprobación')], max_length=20, verbose_name='Tipo de Actividad')),
                ('fecha_vencimiento', models.DateField(help_text='Fecha en que venció la actividad', verbose_name='Fecha de Vencimiento Original')),
                ('fecha_notificacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Notificación Enviada')),
                ('numero_recordatorio', models.IntegerField(default=1, help_text='1 = primer recordatorio, 2 = segundo, 3 = tercero (máximo)', verbose_name='Número de Recordatorio')),
                ('actividad_completada', models.BooleanField(default=False, help_text='True si la actividad fue completada después de enviar notificación', verbose_name='Actividad Completada')),
                ('fecha_ultima_revision', models.DateField(blank=True, help_text='Fecha de la próxima actividad cuando se verificó por última vez', null=True, verbose_name='Fecha Última Revisión')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_vencimiento', to='core.equipo', verbose_name='Equipo')),
            ],
            options={
                'verbose_name': 'Notificación de Vencimiento',
                'verbose_name_plural': 'Notificaciones de Vencimiento',
                'ordering': ['-fecha_notificacion'],
                'indexes': [models.Index(fields=['equipo', 'tipo_actividad', 'fecha_vencimiento'], name='core_notifi_equipo__36492f_idx'), models.Index(fields=['fecha_notificacion'], name='core_notifi_fecha_n_f64993_idx')],
            },
        ),
    ]
