# Generated by Django 5.2.4 on 2025-10-03 19:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_calibracion_tecnico_asignado_sam_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TerminosYCondiciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(help_text='Ejemplo: 1.0, 1.1, 2.0', max_length=20, unique=True, verbose_name='Versión')),
                ('fecha_vigencia', models.DateField(help_text='Fecha desde la cual estos términos están vigentes', verbose_name='Fecha de Vigencia')),
                ('titulo', models.CharField(default='Contrato de Licencia de Uso y Provisión de Servicios SaaS', max_length=255, verbose_name='Título')),
                ('contenido_html', models.TextField(blank=True, help_text='Contenido de los términos en formato HTML', null=True, verbose_name='Contenido HTML')),
                ('archivo_pdf', models.FileField(blank=True, help_text='PDF del contrato firmado', null=True, upload_to='contratos/', verbose_name='Archivo PDF')),
                ('activo', models.BooleanField(default=False, help_text='Solo una versión puede estar activa a la vez', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Términos y Condiciones',
                'verbose_name_plural': 'Términos y Condiciones',
                'ordering': ['-fecha_vigencia', '-version'],
            },
        ),
        migrations.CreateModel(
            name='AceptacionTerminos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_aceptacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Aceptación')),
                ('ip_address', models.GenericIPAddressField(help_text='IP desde la cual se aceptaron los términos', verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, help_text='Información del navegador utilizado', null=True, verbose_name='User Agent')),
                ('aceptado', models.BooleanField(default=True, help_text='Indica si el usuario aceptó los términos', verbose_name='Aceptado')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aceptaciones_terminos', to='core.empresa', verbose_name='Empresa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aceptaciones_terminos', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('terminos', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aceptaciones', to='core.terminosycondiciones', verbose_name='Términos y Condiciones')),
            ],
            options={
                'verbose_name': 'Aceptación de Términos',
                'verbose_name_plural': 'Aceptaciones de Términos',
                'ordering': ['-fecha_aceptacion'],
                'indexes': [models.Index(fields=['usuario', 'terminos'], name='core_acepta_usuario_fafd55_idx'), models.Index(fields=['fecha_aceptacion'], name='core_acepta_fecha_a_52f420_idx')],
                'unique_together': {('usuario', 'terminos')},
            },
        ),
    ]
