# Generated by Django 5.2.4 on 2025-10-07 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_terminosycondiciones_aceptacionterminos'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('backup_db', 'Backup de Base de Datos'), ('clear_cache', 'Limpiar Cache'), ('cleanup_files', 'Limpiar Archivos Temporales'), ('run_tests', 'Ejecutar Tests'), ('check_system', 'Verificar Estado del Sistema'), ('optimize_db', 'Optimizar Base de Datos'), ('collect_static', 'Recolectar Archivos Estáticos'), ('migrate_db', 'Aplicar Migraciones'), ('custom', 'Comando Personalizado')], max_length=50, verbose_name='Tipo de Tarea')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('running', 'Ejecutando'), ('completed', 'Completado'), ('failed', 'Fallido')], default='pending', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Inicio de Ejecución')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fin de Ejecución')),
                ('command', models.TextField(blank=True, help_text="Solo para tipo 'custom'", null=True, verbose_name='Comando Personalizado')),
                ('parameters', models.JSONField(blank=True, default=dict, help_text='Parámetros adicionales en formato JSON', verbose_name='Parámetros')),
                ('output', models.TextField(blank=True, verbose_name='Salida del Comando')),
                ('error_message', models.TextField(blank=True, verbose_name='Mensaje de Error')),
                ('duration_seconds', models.FloatField(blank=True, null=True, verbose_name='Duración (segundos)')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_tasks_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Tarea de Mantenimiento',
                'verbose_name_plural': 'Tareas de Mantenimiento',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommandLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Advertencia'), ('ERROR', 'Error')], default='INFO', max_length=10, verbose_name='Nivel')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.maintenancetask', verbose_name='Tarea')),
            ],
            options={
                'verbose_name': 'Log de Comando',
                'verbose_name_plural': 'Logs de Comandos',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SystemHealthCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Verificación')),
                ('overall_status', models.CharField(choices=[('healthy', 'Saludable'), ('warning', 'Advertencia'), ('critical', 'Crítico')], default='healthy', max_length=20, verbose_name='Estado General')),
                ('database_status', models.CharField(default='unknown', max_length=20)),
                ('cache_status', models.CharField(default='unknown', max_length=20)),
                ('storage_status', models.CharField(default='unknown', max_length=20)),
                ('database_response_time', models.FloatField(blank=True, null=True, verbose_name='Tiempo de Respuesta DB (ms)')),
                ('cache_response_time', models.FloatField(blank=True, null=True, verbose_name='Tiempo de Respuesta Cache (ms)')),
                ('total_empresas', models.IntegerField(default=0)),
                ('total_equipos', models.IntegerField(default=0)),
                ('total_usuarios', models.IntegerField(default=0)),
                ('disk_usage_mb', models.FloatField(blank=True, null=True, verbose_name='Uso de Disco (MB)')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Detalles Adicionales')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Verificado por')),
            ],
            options={
                'verbose_name': 'Verificación de Salud',
                'verbose_name_plural': 'Verificaciones de Salud',
                'ordering': ['-checked_at'],
            },
        ),
        migrations.AddIndex(
            model_name='maintenancetask',
            index=models.Index(fields=['-created_at'], name='core_mainte_created_fcf71d_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancetask',
            index=models.Index(fields=['status'], name='core_mainte_status_1df1a8_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancetask',
            index=models.Index(fields=['task_type'], name='core_mainte_task_ty_6d2bd9_idx'),
        ),
        migrations.AddIndex(
            model_name='commandlog',
            index=models.Index(fields=['-timestamp'], name='core_comman_timesta_832a1a_idx'),
        ),
        migrations.AddIndex(
            model_name='commandlog',
            index=models.Index(fields=['task', '-timestamp'], name='core_comman_task_id_d3015f_idx'),
        ),
        migrations.AddIndex(
            model_name='systemhealthcheck',
            index=models.Index(fields=['-checked_at'], name='core_system_checked_fdf5a7_idx'),
        ),
        migrations.AddIndex(
            model_name='systemhealthcheck',
            index=models.Index(fields=['overall_status'], name='core_system_overall_0842e1_idx'),
        ),
    ]
