# Generated by Django 5.2.4 on 2025-10-15 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_maintenancetask_commandlog_systemhealthcheck_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ziprequest',
            name='rango_equipos_fin',
            field=models.IntegerField(blank=True, null=True, verbose_name='Código Equipo Fin'),
        ),
        migrations.AddField(
            model_name='ziprequest',
            name='rango_equipos_inicio',
            field=models.IntegerField(blank=True, null=True, verbose_name='Código Equipo Inicio'),
        ),
        migrations.AddField(
            model_name='ziprequest',
            name='total_partes',
            field=models.IntegerField(default=1, verbose_name='Total de Partes'),
        ),
    ]
