# Generated by Django 5.2.4 on 2025-11-10 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_ziprequest_rango_equipos_fin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='puntos_calibracion',
            field=models.TextField(blank=True, null=True, verbose_name='Puntos de Calibración'),
        ),
    ]
