# Generated by Django 5.2.4 on 2025-11-27 18:25

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_equipo_puntos_calibracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobacion',
            name='analisis_interno',
            field=models.FileField(blank=True, null=True, upload_to=core.models.get_upload_path, verbose_name='Análisis Interno (PDF/Excel)'),
        ),
        migrations.AddField(
            model_name='comprobacion',
            name='documento_externo',
            field=models.FileField(blank=True, null=True, upload_to=core.models.get_upload_path, verbose_name='Documento Externo (PDF/Excel)'),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='analisis_interno',
            field=models.FileField(blank=True, null=True, upload_to=core.models.get_upload_path, verbose_name='Análisis Interno (PDF/Excel)'),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='documento_externo',
            field=models.FileField(blank=True, null=True, upload_to=core.models.get_upload_path, verbose_name='Documento Externo (PDF/Excel)'),
        ),
        migrations.AlterField(
            model_name='comprobacion',
            name='documento_comprobacion',
            field=models.FileField(blank=True, null=True, upload_to=core.models.get_upload_path, verbose_name='Documento General de Comprobación (PDF)'),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='documento_mantenimiento',
            field=models.FileField(blank=True, null=True, upload_to=core.models.get_upload_path, verbose_name='Documento General de Mantenimiento (PDF)'),
        ),
    ]
