# Generated by Django 5.2.4 on 2025-11-27 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_agregar_documentos_externos_analisis_internos'),
    ]

    operations = [
        # Índices para búsquedas frecuentes en Equipo
        migrations.AddIndex(
            model_name='equipo',
            index=models.Index(fields=['codigo_interno'], name='core_equipo_codigo_idx'),
        ),
        migrations.AddIndex(
            model_name='equipo',
            index=models.Index(fields=['nombre'], name='core_equipo_nombre_idx'),
        ),
        migrations.AddIndex(
            model_name='equipo',
            index=models.Index(fields=['empresa', 'codigo_interno'], name='core_equipo_emp_cod_idx'),
        ),

        # Índices para fechas de actividades (usado en reportes y dashboard)
        migrations.AddIndex(
            model_name='calibracion',
            index=models.Index(fields=['fecha_calibracion'], name='core_cal_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='mantenimiento',
            index=models.Index(fields=['fecha_mantenimiento'], name='core_mant_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='comprobacion',
            index=models.Index(fields=['fecha_comprobacion'], name='core_comp_fecha_idx'),
        ),

        # Índices para relaciones frecuentes
        migrations.AddIndex(
            model_name='calibracion',
            index=models.Index(fields=['equipo', 'fecha_calibracion'], name='core_cal_eq_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='mantenimiento',
            index=models.Index(fields=['equipo', 'fecha_mantenimiento'], name='core_mant_eq_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='comprobacion',
            index=models.Index(fields=['equipo', 'fecha_comprobacion'], name='core_comp_eq_fecha_idx'),
        ),
    ]
