# Generated by Django 5.2.4 on 2025-12-01 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_agregar_indices_performance'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='calibracion',
            name='core_cal_fecha_idx',
        ),
        migrations.RemoveIndex(
            model_name='calibracion',
            name='core_cal_eq_fecha_idx',
        ),
        migrations.RemoveIndex(
            model_name='comprobacion',
            name='core_comp_fecha_idx',
        ),
        migrations.RemoveIndex(
            model_name='comprobacion',
            name='core_comp_eq_fecha_idx',
        ),
        migrations.RemoveIndex(
            model_name='equipo',
            name='core_equipo_codigo_idx',
        ),
        migrations.RemoveIndex(
            model_name='equipo',
            name='core_equipo_nombre_idx',
        ),
        migrations.RemoveIndex(
            model_name='equipo',
            name='core_equipo_emp_cod_idx',
        ),
        migrations.RemoveIndex(
            model_name='mantenimiento',
            name='core_mant_fecha_idx',
        ),
        migrations.RemoveIndex(
            model_name='mantenimiento',
            name='core_mant_eq_fecha_idx',
        ),
        migrations.AddField(
            model_name='calibracion',
            name='confirmacion_metrologica_datos',
            field=models.JSONField(blank=True, help_text='Almacena puntos de medición, errores y desviaciones para cálculo de deriva', null=True, verbose_name='Datos de Confirmación Metrológica'),
        ),
    ]
