# Generated by Django 5.2.4 on 2025-12-04 00:55

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_remove_calibracion_core_cal_fecha_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobacion',
            name='comprobacion_pdf',
            field=models.FileField(blank=True, null=True, upload_to=core.models.get_upload_path, verbose_name='PDF de Comprobación Metrológica'),
        ),
        migrations.AddField(
            model_name='comprobacion',
            name='datos_comprobacion',
            field=models.JSONField(blank=True, help_text='Datos JSON con puntos de medición, tolerancias y conformidad', null=True, verbose_name='Datos de Comprobación Metrológica'),
        ),
    ]
