# Generated by Django 5.2.4 on 2025-12-04 17:15

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_comprobacion_comprobacion_pdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantenimiento',
            name='actividades_realizadas',
            field=models.JSONField(blank=True, help_text='Actividades detalladas del mantenimiento en formato JSON', null=True, verbose_name='Actividades Realizadas'),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='mantenimiento_pdf',
            field=models.FileField(blank=True, null=True, upload_to=core.models.get_upload_path, verbose_name='PDF de Mantenimiento Generado'),
        ),
    ]
