# Generated by Django 5.2.4 on 2025-12-06 00:23

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_mantenimiento_actividades_realizadas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobacion',
            name='documento_interno',
            field=models.FileField(blank=True, null=True, upload_to=core.models.get_upload_path, verbose_name='Documento Interno (SAM)'),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='documento_interno',
            field=models.FileField(blank=True, null=True, upload_to=core.models.get_upload_path, verbose_name='Documento Interno (SAM)'),
        ),
    ]
