# Generated by Django 5.2.4 on 2025-12-06 00:37

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_add_documento_externo_interno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calibracion',
            name='confirmacion_metrologica_datos',
            field=models.JSONField(blank=True, help_text='Datos JSON con puntos de medición, incertidumbres y cálculos', null=True, verbose_name='Datos de Confirmación Metrológica'),
        ),
        migrations.AlterField(
            model_name='comprobacion',
            name='documento_comprobacion',
            field=models.FileField(blank=True, null=True, upload_to=core.models.get_upload_path, verbose_name='Documento de Comprobación (PDF)'),
        ),
        migrations.AlterField(
            model_name='comprobacion',
            name='documento_externo',
            field=models.FileField(blank=True, null=True, upload_to=core.models.get_upload_path, verbose_name='Documento Externo (Proveedor)'),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='documento_externo',
            field=models.FileField(blank=True, null=True, upload_to=core.models.get_upload_path, verbose_name='Documento Externo (Proveedor)'),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='documento_mantenimiento',
            field=models.FileField(blank=True, null=True, upload_to=core.models.get_upload_path, verbose_name='Documento de Mantenimiento (PDF)'),
        ),
    ]
