# Generated by Django 5.2.4 on 2025-12-28 00:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_remove_comprobacion_analisis_interno_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comprobacion',
            name='analisis_interno',
        ),
        migrations.RemoveField(
            model_name='mantenimiento',
            name='analisis_interno',
        ),
        migrations.RemoveField(
            model_name='mantenimiento',
            name='mantenimiento_pdf',
        ),
        migrations.CreateModel(
            name='AgrupacionPrestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Set Termómetros Proceso A', max_length=255, verbose_name='Nombre de la Agrupación')),
                ('prestatario_nombre', models.CharField(max_length=255, verbose_name='Nombre del Prestatario')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agrupaciones_prestamo', to='core.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Agrupación de Préstamo',
                'verbose_name_plural': 'Agrupaciones de Préstamos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='PrestamoEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_prestatario', models.CharField(max_length=255, verbose_name='Nombre del Prestatario')),
                ('cedula_prestatario', models.CharField(blank=True, max_length=50, verbose_name='Cédula del Prestatario')),
                ('cargo_prestatario', models.CharField(blank=True, max_length=255, verbose_name='Cargo del Prestatario')),
                ('email_prestatario', models.EmailField(blank=True, max_length=254, verbose_name='Email del Prestatario')),
                ('telefono_prestatario', models.CharField(blank=True, max_length=50, verbose_name='Teléfono del Prestatario')),
                ('fecha_prestamo', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Préstamo')),
                ('fecha_devolucion_programada', models.DateField(blank=True, null=True, verbose_name='Fecha de Devolución Programada')),
                ('fecha_devolucion_real', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Devolución Real')),
                ('estado_prestamo', models.CharField(choices=[('ACTIVO', 'En Préstamo'), ('DEVUELTO', 'Devuelto'), ('VENCIDO', 'Vencido (no devuelto a tiempo)'), ('CANCELADO', 'Cancelado')], default='ACTIVO', max_length=20, verbose_name='Estado del Préstamo')),
                ('verificacion_salida', models.JSONField(blank=True, help_text='Datos de verificación funcional al momento del préstamo', null=True, verbose_name='Verificación Funcional de Salida')),
                ('verificacion_entrada', models.JSONField(blank=True, help_text='Datos de verificación funcional al momento de devolución', null=True, verbose_name='Verificación Funcional de Entrada')),
                ('actividades_realizadas', models.JSONField(blank=True, help_text='Historial de actividades realizadas con el equipo durante préstamo', null=True, verbose_name='Actividades Realizadas')),
                ('documento_prestamo', models.FileField(blank=True, null=True, upload_to='prestamos/', verbose_name='Acta de Préstamo (PDF)')),
                ('documento_devolucion', models.FileField(blank=True, null=True, upload_to='prestamos/', verbose_name='Acta de Devolución (PDF)')),
                ('observaciones_prestamo', models.TextField(blank=True, verbose_name='Observaciones del Préstamo')),
                ('observaciones_devolucion', models.TextField(blank=True, verbose_name='Observaciones de la Devolución')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('agrupacion', models.ForeignKey(blank=True, help_text='Opcional: agrupa múltiples préstamos relacionados', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prestamos', to='core.agrupacionprestamo', verbose_name='Agrupación')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos_equipos', to='core.empresa', verbose_name='Empresa')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to='core.equipo', verbose_name='Equipo')),
                ('prestado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prestamos_autorizados', to=settings.AUTH_USER_MODEL, verbose_name='Prestado por')),
                ('recibido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devoluciones_recibidas', to=settings.AUTH_USER_MODEL, verbose_name='Recibido por')),
            ],
            options={
                'verbose_name': 'Préstamo de Equipo',
                'verbose_name_plural': 'Préstamos de Equipos',
                'ordering': ['-fecha_prestamo'],
                'permissions': [('can_view_prestamo', 'Can view préstamo'), ('can_add_prestamo', 'Can add préstamo'), ('can_change_prestamo', 'Can change préstamo'), ('can_delete_prestamo', 'Can delete préstamo'), ('can_view_all_prestamos', 'Can view all company préstamos')],
            },
        ),
    ]
