# Generated by Django 5.2.4 on 2026-01-20 14:50

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Migración para agregar índices de rendimiento en el modelo Equipo.

    Índices agregados:
    - estado: Filtros frecuentes por estado de equipo
    - proxima_calibracion: Queries de alertas y vencimientos
    - proximo_mantenimiento: Queries de alertas y vencimientos
    - proxima_comprobacion: Queries de alertas y vencimientos
    - (empresa, estado): Índice compuesto para filtros combinados
    - (empresa, proxima_calibracion): Para queries de empresa + fecha
    - (empresa, proximo_mantenimiento): Para queries de empresa + fecha
    - (empresa, proxima_comprobacion): Para queries de empresa + fecha

    Impacto esperado: Mejora en dashboard y reportes (20-40% más rápido)
    """

    dependencies = [
        ('core', '0044_add_prestamo_models'),
    ]

    operations = [
        # Índices simples para campos individuales
        migrations.AddIndex(
            model_name='equipo',
            index=models.Index(fields=['estado'], name='equipo_estado_idx'),
        ),
        migrations.AddIndex(
            model_name='equipo',
            index=models.Index(fields=['proxima_calibracion'], name='equipo_prox_cal_idx'),
        ),
        migrations.AddIndex(
            model_name='equipo',
            index=models.Index(fields=['proximo_mantenimiento'], name='equipo_prox_mant_idx'),
        ),
        migrations.AddIndex(
            model_name='equipo',
            index=models.Index(fields=['proxima_comprobacion'], name='equipo_prox_comp_idx'),
        ),

        # Índices compuestos para queries combinadas
        migrations.AddIndex(
            model_name='equipo',
            index=models.Index(fields=['empresa', 'estado'], name='equipo_emp_est_idx'),
        ),
        migrations.AddIndex(
            model_name='equipo',
            index=models.Index(fields=['empresa', 'proxima_calibracion'], name='equipo_emp_pcal_idx'),
        ),
        migrations.AddIndex(
            model_name='equipo',
            index=models.Index(fields=['empresa', 'proximo_mantenimiento'], name='equipo_emp_pmant_idx'),
        ),
        migrations.AddIndex(
            model_name='equipo',
            index=models.Index(fields=['empresa', 'proxima_comprobacion'], name='equipo_emp_pcomp_idx'),
        ),
    ]
