# Generated by Django 5.2.4 on 2026-01-21 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_add_performance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='equipo',
            name='equipo_estado_idx',
        ),
        migrations.RemoveIndex(
            model_name='equipo',
            name='equipo_prox_cal_idx',
        ),
        migrations.RemoveIndex(
            model_name='equipo',
            name='equipo_prox_mant_idx',
        ),
        migrations.RemoveIndex(
            model_name='equipo',
            name='equipo_prox_comp_idx',
        ),
        migrations.RemoveIndex(
            model_name='equipo',
            name='equipo_emp_est_idx',
        ),
        migrations.RemoveIndex(
            model_name='equipo',
            name='equipo_emp_pcal_idx',
        ),
        migrations.RemoveIndex(
            model_name='equipo',
            name='equipo_emp_pmant_idx',
        ),
        migrations.RemoveIndex(
            model_name='equipo',
            name='equipo_emp_pcomp_idx',
        ),
        migrations.AddField(
            model_name='comprobacion',
            name='equipo_referencia_certificado',
            field=models.CharField(blank=True, help_text='Número de certificado de calibración del equipo de referencia', max_length=100, null=True, verbose_name='Equipo de Referencia - Certificado de Calibración'),
        ),
        migrations.AddField(
            model_name='comprobacion',
            name='equipo_referencia_marca',
            field=models.CharField(blank=True, help_text='Marca del equipo de referencia', max_length=100, null=True, verbose_name='Equipo de Referencia - Marca'),
        ),
        migrations.AddField(
            model_name='comprobacion',
            name='equipo_referencia_modelo',
            field=models.CharField(blank=True, help_text='Modelo del equipo de referencia', max_length=100, null=True, verbose_name='Equipo de Referencia - Modelo'),
        ),
        migrations.AddField(
            model_name='comprobacion',
            name='equipo_referencia_nombre',
            field=models.CharField(blank=True, help_text='Nombre del equipo de referencia utilizado en la comprobación', max_length=255, null=True, verbose_name='Equipo de Referencia - Nombre'),
        ),
    ]
