# Generated by Django 5.2.4 on 2026-01-21 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_agregar_equipo_referencia_comprobacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='comprobacion_codigo',
            field=models.CharField(blank=True, default='SAM-COMP-001', help_text='Código del formato de comprobación metrológica (ej: SAM-COMP-001)', max_length=100, null=True, verbose_name='Código Formato - Comprobación Metrológica'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='comprobacion_fecha_formato',
            field=models.DateField(blank=True, help_text='Fecha de emisión/actualización del formato de comprobación metrológica', null=True, verbose_name='Fecha del Formato - Comprobación Metrológica'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='comprobacion_version',
            field=models.CharField(blank=True, default='01', help_text='Versión del formato de comprobación metrológica (ej: 01, 02, 03)', max_length=50, null=True, verbose_name='Versión Formato - Comprobación Metrológica'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='confirmacion_codigo',
            field=models.CharField(blank=True, default='SAM-CONF-001', help_text='Código del formato de confirmación metrológica (ej: SAM-CONF-001)', max_length=100, null=True, verbose_name='Código Formato - Confirmación Metrológica'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='confirmacion_fecha_formato',
            field=models.DateField(blank=True, help_text='Fecha de emisión/actualización del formato de confirmación metrológica', null=True, verbose_name='Fecha del Formato - Confirmación Metrológica'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='confirmacion_version',
            field=models.CharField(blank=True, default='01', help_text='Versión del formato de confirmación metrológica (ej: 01, 02, 03)', max_length=50, null=True, verbose_name='Versión Formato - Confirmación Metrológica'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='intervalos_codigo',
            field=models.CharField(blank=True, default='SAM-INT-001', help_text='Código del formato de intervalos de calibración (ej: SAM-INT-001)', max_length=100, null=True, verbose_name='Código Formato - Intervalos de Calibración'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='intervalos_fecha_formato',
            field=models.DateField(blank=True, help_text='Fecha de emisión/actualización del formato de intervalos de calibración', null=True, verbose_name='Fecha del Formato - Intervalos de Calibración'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='intervalos_version',
            field=models.CharField(blank=True, default='01', help_text='Versión del formato de intervalos de calibración (ej: 01, 02, 03)', max_length=50, null=True, verbose_name='Versión Formato - Intervalos de Calibración'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='mantenimiento_codigo',
            field=models.CharField(blank=True, default='SAM-MANT-001', help_text='Código del formato de mantenimiento (ej: SAM-MANT-001)', max_length=100, null=True, verbose_name='Código Formato - Mantenimiento'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='mantenimiento_fecha_formato',
            field=models.DateField(blank=True, help_text='Fecha de emisión/actualización del formato de mantenimiento', null=True, verbose_name='Fecha del Formato - Mantenimiento'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='mantenimiento_version',
            field=models.CharField(blank=True, default='01', help_text='Versión del formato de mantenimiento (ej: 01, 02, 03)', max_length=50, null=True, verbose_name='Versión Formato - Mantenimiento'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='formato_codificacion_empresa',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Codificación del Formato (Empresa) - DEPRECADO'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='formato_fecha_version_empresa',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Versión del Formato (Empresa) - DEPRECADO'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='formato_version_empresa',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Versión del Formato (Empresa) - DEPRECADO'),
        ),
    ]
