# Generated by Django 5.2.4 on 2026-01-23 01:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_sistema_aprobacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calibracion',
            name='aprobado_por',
            field=models.ForeignKey(blank=True, help_text='Usuario que aprobó la confirmación o intervalos', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calibraciones_aprobadas', to=settings.AUTH_USER_MODEL, verbose_name='Aprobado por'),
        ),
        migrations.AlterField(
            model_name='calibracion',
            name='creado_por',
            field=models.ForeignKey(blank=True, help_text='Usuario que creó el documento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calibraciones_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AlterField(
            model_name='calibracion',
            name='observaciones_rechazo',
            field=models.TextField(blank=True, help_text='Razón por la cual se rechazó el documento', null=True, verbose_name='Observaciones de Rechazo'),
        ),
        migrations.AlterField(
            model_name='comprobacion',
            name='aprobado_por',
            field=models.ForeignKey(blank=True, help_text='Usuario que aprobó la comprobación', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comprobaciones_aprobadas', to=settings.AUTH_USER_MODEL, verbose_name='Aprobado por'),
        ),
        migrations.AlterField(
            model_name='comprobacion',
            name='creado_por',
            field=models.ForeignKey(blank=True, help_text='Usuario que creó el documento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comprobaciones_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AlterField(
            model_name='comprobacion',
            name='observaciones_rechazo',
            field=models.TextField(blank=True, help_text='Razón por la cual se rechazó el documento', null=True, verbose_name='Observaciones de Rechazo'),
        ),
    ]
