# Generated by Django 5.2.4 on 2026-01-23 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_separar_estados_aprobacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calibracion',
            name='aprobado_por',
            field=models.ForeignKey(blank=True, help_text='DEPRECATED - Usar confirmacion_aprobado_por o intervalos_aprobado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calibraciones_aprobadas', to=settings.AUTH_USER_MODEL, verbose_name='Aprobado por (legacy)'),
        ),
        migrations.AlterField(
            model_name='calibracion',
            name='estado_aprobacion',
            field=models.CharField(choices=[('pendiente', 'Pendiente de Aprobación'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20, verbose_name='Estado de Aprobación (legacy)'),
        ),
        migrations.AlterField(
            model_name='calibracion',
            name='fecha_aprobacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Aprobación (legacy)'),
        ),
        migrations.AlterField(
            model_name='calibracion',
            name='observaciones_rechazo',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones de Rechazo (legacy)'),
        ),
    ]
