# Generated by Django 5.2.4 on 2026-01-23 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_agregar_proveedor_equipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibracion',
            name='confirmacion_fecha_aprobacion_ajustable',
            field=models.DateField(blank=True, help_text='Fecha de aprobación mostrada en PDF (ajustable para auditoría)', null=True, verbose_name='Fecha de Aprobación Ajustable - Confirmación'),
        ),
        migrations.AddField(
            model_name='calibracion',
            name='confirmacion_fecha_emision',
            field=models.DateField(blank=True, help_text='Fecha de emisión del documento (ajustable para auditoría)', null=True, verbose_name='Fecha de Emisión PDF - Confirmación'),
        ),
        migrations.AddField(
            model_name='calibracion',
            name='confirmacion_fecha_realizacion',
            field=models.DateField(blank=True, help_text='Fecha en que se realizó la actividad (ajustable para auditoría)', null=True, verbose_name='Fecha de Realización - Confirmación'),
        ),
        migrations.AddField(
            model_name='calibracion',
            name='intervalos_fecha_aprobacion_ajustable',
            field=models.DateField(blank=True, help_text='Fecha de aprobación mostrada en PDF (ajustable para auditoría)', null=True, verbose_name='Fecha de Aprobación Ajustable - Intervalos'),
        ),
        migrations.AddField(
            model_name='calibracion',
            name='intervalos_fecha_emision',
            field=models.DateField(blank=True, help_text='Fecha de emisión del documento (ajustable para auditoría)', null=True, verbose_name='Fecha de Emisión PDF - Intervalos'),
        ),
        migrations.AddField(
            model_name='calibracion',
            name='intervalos_fecha_realizacion',
            field=models.DateField(blank=True, help_text='Fecha en que se realizó la actividad (ajustable para auditoría)', null=True, verbose_name='Fecha de Realización - Intervalos'),
        ),
        migrations.AddField(
            model_name='comprobacion',
            name='fecha_aprobacion_ajustable',
            field=models.DateField(blank=True, help_text='Fecha de aprobación mostrada en PDF (ajustable para auditoría)', null=True, verbose_name='Fecha de Aprobación Ajustable'),
        ),
        migrations.AddField(
            model_name='comprobacion',
            name='fecha_emision',
            field=models.DateField(blank=True, help_text='Fecha de emisión del documento (ajustable para auditoría)', null=True, verbose_name='Fecha de Emisión PDF'),
        ),
        migrations.AddField(
            model_name='comprobacion',
            name='fecha_realizacion',
            field=models.DateField(blank=True, help_text='Fecha en que se realizó la actividad (ajustable para auditoría)', null=True, verbose_name='Fecha de Realización'),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='fecha_aprobacion_ajustable',
            field=models.DateField(blank=True, help_text='Fecha de aprobación mostrada en PDF (ajustable para auditoría)', null=True, verbose_name='Fecha de Aprobación Ajustable'),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='fecha_emision',
            field=models.DateField(blank=True, help_text='Fecha de emisión del documento (ajustable para auditoría)', null=True, verbose_name='Fecha de Emisión PDF'),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='fecha_realizacion',
            field=models.DateField(blank=True, help_text='Fecha en que se realizó la actividad (ajustable para auditoría)', null=True, verbose_name='Fecha de Realización'),
        ),
    ]
