# Generated by Django 5.2.4 on 2026-01-24 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_agregar_fechas_ajustables_auditoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='comprobacion_fecha_formato_display',
            field=models.CharField(blank=True, help_text='Formato de fecha para mostrar (YYYY-MM o YYYY-MM-DD)', max_length=10, null=True, verbose_name='Fecha Formato Display - Comprobación'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='confirmacion_fecha_formato_display',
            field=models.CharField(blank=True, help_text='Formato de fecha para mostrar (YYYY-MM o YYYY-MM-DD)', max_length=10, null=True, verbose_name='Fecha Formato Display - Confirmación'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='formato_fecha_version_empresa_display',
            field=models.CharField(blank=True, help_text='Formato de fecha para mostrar (YYYY-MM o YYYY-MM-DD)', max_length=10, null=True, verbose_name='Fecha Formato Display - Empresa (General)'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='intervalos_fecha_formato_display',
            field=models.CharField(blank=True, help_text='Formato de fecha para mostrar (YYYY-MM o YYYY-MM-DD)', max_length=10, null=True, verbose_name='Fecha Formato Display - Intervalos'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='mantenimiento_fecha_formato_display',
            field=models.CharField(blank=True, help_text='Formato de fecha para mostrar (YYYY-MM o YYYY-MM-DD)', max_length=10, null=True, verbose_name='Fecha Formato Display - Mantenimiento'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='fecha_version_formato_display',
            field=models.CharField(blank=True, help_text='Formato de fecha para mostrar (YYYY-MM o YYYY-MM-DD)', max_length=10, null=True, verbose_name='Fecha Formato Display - Hoja de Vida'),
        ),
    ]
