# Generated by Django 5.2.4 on 2026-01-28 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_agregar_display_fechas_formato'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibracion',
            name='intervalos_calibracion_datos',
            field=models.JSONField(blank=True, help_text='Datos JSON con método, cálculos y decisión de intervalos', null=True, verbose_name='Datos de Intervalos de Calibración'),
        ),
        migrations.AddField(
            model_name='comprobacion',
            name='consecutivo',
            field=models.PositiveIntegerField(blank=True, help_text='Número consecutivo de comprobación por empresa', null=True, verbose_name='Consecutivo'),
        ),
        migrations.AddField(
            model_name='comprobacion',
            name='empresa_cliente',
            field=models.ForeignKey(blank=True, help_text='Empresa cliente registrada en el sistema', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comprobaciones_como_cliente', to='core.empresa', verbose_name='Empresa Cliente (existente)'),
        ),
        migrations.AddField(
            model_name='comprobacion',
            name='empresa_cliente_direccion',
            field=models.CharField(blank=True, help_text='Dirección de la empresa cliente', max_length=255, null=True, verbose_name='Dirección Empresa Cliente'),
        ),
        migrations.AddField(
            model_name='comprobacion',
            name='empresa_cliente_nit',
            field=models.CharField(blank=True, help_text='NIT de la empresa cliente', max_length=50, null=True, verbose_name='NIT Empresa Cliente'),
        ),
        migrations.AddField(
            model_name='comprobacion',
            name='empresa_cliente_nombre',
            field=models.CharField(blank=True, help_text='Nombre de la empresa cliente (si no está registrada)', max_length=255, null=True, verbose_name='Nombre Empresa Cliente'),
        ),
        migrations.AddField(
            model_name='comprobacion',
            name='es_servicio_terceros',
            field=models.BooleanField(default=False, help_text='Indica si esta comprobación es un servicio para un cliente externo', verbose_name='Servicio a terceros'),
        ),
    ]
