# Generated by Django 5.2.4 on 2026-01-29 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_agregar_consecutivo_empresa_cliente_comprobaciones_intervalos_datos'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='comprobacion_prefijo_consecutivo',
            field=models.CharField(blank=True, default='CB', help_text='Prefijo para numerar comprobaciones (ej: CB, COMP). Resultado: CB-001, CB-002...', max_length=10, verbose_name='Prefijo Consecutivo Comprobaciones'),
        ),
    ]
