# Generated by Django 5.2.4 on 2026-01-29 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_agregar_prefijo_consecutivo_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobacion',
            name='consecutivo_texto',
            field=models.CharField(blank=True, help_text='Consecutivo visible en el PDF (texto libre, ej: CB-001, COMP-2026-01)', max_length=50, null=True, verbose_name='Consecutivo'),
        ),
        migrations.AlterField(
            model_name='comprobacion',
            name='consecutivo',
            field=models.PositiveIntegerField(blank=True, help_text='Número consecutivo interno de comprobación por empresa', null=True, verbose_name='Consecutivo (interno)'),
        ),
    ]
