# Generated by Django 5.2.4 on 2026-01-29 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_agregar_consecutivo_texto_comprobacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='listado_codigo',
            field=models.CharField(blank=True, default='SAM-LIST-001', help_text='Código del formato de listado de equipos (ej: SAM-LIST-001)', max_length=100, null=True, verbose_name='Código Formato - Listado de Equipos'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='listado_fecha_formato',
            field=models.DateField(blank=True, help_text='Fecha de emisión/actualización del formato de listado de equipos', null=True, verbose_name='Fecha del Formato - Listado de Equipos'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='listado_fecha_formato_display',
            field=models.CharField(blank=True, help_text='Formato de fecha para mostrar (YYYY-MM o YYYY-MM-DD)', max_length=10, null=True, verbose_name='Fecha Formato Display - Listado de Equipos'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='listado_version',
            field=models.CharField(blank=True, default='01', help_text='Versión del formato de listado de equipos (ej: 01, 02, 03)', max_length=50, null=True, verbose_name='Versión Formato - Listado de Equipos'),
        ),
    ]
