# Generated by Django 5.2.4 on 2026-02-03 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_revertir_aprobaciones_equipos_afectados'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='comprobacion_observaciones_formato',
            field=models.TextField(blank=True, help_text='Observaciones o notas que aparecerán en todos los PDFs de comprobación metrológica', null=True, verbose_name='Observaciones del Formato - Comprobación'),
        ),
    ]
