# Generated by Django 5.2.11 on 2026-02-21 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_agregar_comprobacion_observaciones_formato'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_completado', models.BooleanField(default=False)),
                ('paso_crear_equipo', models.BooleanField(default=False)),
                ('paso_registrar_calibracion', models.BooleanField(default=False)),
                ('paso_generar_reporte', models.BooleanField(default=False)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_completado', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Progreso de Onboarding',
                'verbose_name_plural': 'Progresos de Onboarding',
            },
        ),
    ]
