# Generated by Django 5.2.11 on 2026-02-23 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_onboardingprogress'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransaccionPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia_pago', models.CharField(help_text='ID único de la transacción (enviado a Wompi como reference)', max_length=100, unique=True, verbose_name='Referencia de Pago')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('error', 'Error')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('monto', models.DecimalField(decimal_places=2, help_text='Valor total incluyendo IVA, en COP', max_digits=12, verbose_name='Monto')),
                ('moneda', models.CharField(default='COP', max_length=3, verbose_name='Moneda')),
                ('metodo_pago', models.CharField(blank=True, choices=[('PSE', 'PSE'), ('tarjeta', 'Tarjeta de Crédito/Débito'), ('efectivo', 'Efectivo')], max_length=20, verbose_name='Método de Pago')),
                ('plan_seleccionado', models.CharField(choices=[('MENSUAL', 'Plan Mensual'), ('ANUAL', 'Plan Anual')], max_length=20, verbose_name='Plan Seleccionado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('datos_respuesta', models.JSONField(blank=True, help_text='Respuesta completa de Wompi (para auditoría)', null=True, verbose_name='Datos de Respuesta')),
                ('ip_cliente', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP del Cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones_pago', to='core.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Transacción de Pago',
                'verbose_name_plural': 'Transacciones de Pago',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
