# Generated by Django 5.2.11 on 2026-02-23 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_add_transaccion_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccionpago',
            name='plan_seleccionado',
            field=models.CharField(choices=[('MENSUAL', 'Plan Estándar Mensual'), ('ANUAL', 'Plan Estándar Anual'), ('BASICO_MENSUAL', 'Plan Básico Mensual'), ('BASICO_ANUAL', 'Plan Básico Anual'), ('PRO_MENSUAL', 'Plan Profesional Mensual'), ('PRO_ANUAL', 'Plan Profesional Anual'), ('ENTERPRISE_MENSUAL', 'Plan Empresarial Mensual'), ('ENTERPRISE_ANUAL', 'Plan Empresarial Anual')], max_length=20, verbose_name='Plan Seleccionado'),
        ),
    ]
