# Generated by Django 5.2.11 on 2026-02-23 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_expand_plan_choices_transaccionpago'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='limite_usuarios_empresa',
            field=models.IntegerField(default=3, help_text='Máximo de usuarios activos permitidos. Base: 3 (técnico, admin, gerente).', verbose_name='Límite de Usuarios'),
        ),
        migrations.AddField(
            model_name='transaccionpago',
            name='datos_addon',
            field=models.JSONField(blank=True, help_text='Cantidades de add-ons comprados: {tecnicos, admins, gerentes, bloques_equipos, bloques_storage}', null=True, verbose_name='Detalle de Add-ons'),
        ),
        migrations.AlterField(
            model_name='transaccionpago',
            name='plan_seleccionado',
            field=models.CharField(blank=True, choices=[('MENSUAL', 'Plan Estándar Mensual'), ('ANUAL', 'Plan Estándar Anual'), ('BASICO_MENSUAL', 'Plan Básico Mensual'), ('BASICO_ANUAL', 'Plan Básico Anual'), ('PRO_MENSUAL', 'Plan Profesional Mensual'), ('PRO_ANUAL', 'Plan Profesional Anual'), ('ENTERPRISE_MENSUAL', 'Plan Empresarial Mensual'), ('ENTERPRISE_ANUAL', 'Plan Empresarial Anual'), ('ADDON', 'Add-ons')], help_text='Vacío solo para transacciones de tipo add-on cuando se usa el campo datos_addon', max_length=20, verbose_name='Plan Seleccionado'),
        ),
    ]
