# Generated by Django 5.2.11 on 2026-02-27 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_add_addon_fields_empresa_transaccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='correos_facturacion',
            field=models.TextField(blank=True, help_text='Correos adicionales para recibir facturas (separados por coma). Ej: admin@empresa.com, gerente@empresa.com', null=True, verbose_name='Correos de Facturación'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='correos_notificaciones',
            field=models.TextField(blank=True, help_text='Correos adicionales para notificaciones del sistema (separados por coma). Ej: tecnico@empresa.com, supervisor@empresa.com', null=True, verbose_name='Correos de Notificaciones'),
        ),
    ]
