# Generated by Django 5.2.11 on 2026-02-27 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_empresa_correos_facturacion_notificaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='configurar_usuarios_plan_pendiente',
            field=models.BooleanField(default=False, help_text='True si el cliente debe configurar sus usuarios al próximo login (post-compra de plan)', verbose_name='Configuración de Usuarios Pendiente'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='slots_usuarios_pendientes',
            field=models.JSONField(blank=True, default=dict, help_text='Usuarios comprados pero no creados: {tecnicos: N, admins: N, gerentes: N}', null=True, verbose_name='Slots de Usuarios Pendientes'),
        ),
    ]
