# Generated by Django 5.2.11 on 2026-03-03 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_empresa_setup_usuarios_pendiente'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='renovacion_automatica',
            field=models.BooleanField(default=False, verbose_name='Renovación Automática'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='wompi_payment_source_id',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Wompi Payment Source ID'),
        ),
    ]
