# Generated by Django 5.2.11 on 2026-03-03 03:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_empresa_renovacion_automatica'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='addons_recurrentes',
            field=models.JSONField(blank=True, default=dict, help_text='Add-ons que se cobran automáticamente en cada renovación: {tecnicos, admins, gerentes, bloques_equipos, bloques_storage}', verbose_name='Add-ons Recurrentes'),
        ),
        migrations.CreateModel(
            name='LinkPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('plan_seleccionado', models.CharField(blank=True, max_length=40, null=True, verbose_name='Plan seleccionado')),
                ('addons', models.JSONField(blank=True, default=dict, help_text='{tecnicos, admins, gerentes, bloques_equipos, bloques_storage}', verbose_name='Add-ons')),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto total (IVA incl.)')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('expirado', 'Expirado')], default='pendiente', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_expiracion', models.DateTimeField()),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='links_pago_creados', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_pago', to='core.empresa', verbose_name='Empresa')),
                ('transaccion', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='link_pago', to='core.transaccionpago')),
            ],
            options={
                'verbose_name': 'Link de Pago',
                'verbose_name_plural': 'Links de Pago',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
