# Generated by Django 5.2.11 on 2026-03-11 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_empresa_addons_recurrentes_linkpago'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='stats_calibraciones_proximas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='empresa',
            name='stats_calibraciones_vencidas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='empresa',
            name='stats_compliance_calibracion',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='empresa',
            name='stats_compliance_comprobacion',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='empresa',
            name='stats_compliance_mantenimiento',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='empresa',
            name='stats_comprobaciones_proximas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='empresa',
            name='stats_comprobaciones_vencidas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='empresa',
            name='stats_equipos_activos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='empresa',
            name='stats_equipos_de_baja',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='empresa',
            name='stats_equipos_inactivos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='empresa',
            name='stats_fecha_calculo',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='stats_mantenimientos_proximos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='empresa',
            name='stats_mantenimientos_vencidos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='empresa',
            name='stats_total_equipos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='empresa',
            name='stats_ultima_actualizacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
