# Generated by Django 5.2.12 on 2026-04-30 22:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_comprobacion_equipos_referencia_adicionales'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaFormatoLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo', models.CharField(max_length=100)),
                ('valor_anterior', models.CharField(blank=True, default='', max_length=200)),
                ('valor_nuevo', models.CharField(blank=True, default='', max_length=200)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formato_logs', to='core.empresa')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de formato',
                'verbose_name_plural': 'Historial de formatos',
                'ordering': ['-fecha'],
            },
        ),
    ]
