# Generated by Django 5.2.12 on 2026-05-01 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_add_empresa_formato_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='entidad_acreditadora',
            field=models.CharField(blank=True, choices=[('ONAC', 'ONAC (Colombia)'), ('IDEAM', 'IDEAM (Colombia)'), ('ILAC', 'Miembro ILAC'), ('DAkkS', 'DAkkS (Alemania)'), ('UKAS', 'UKAS (Reino Unido)'), ('A2LA', 'A2LA (EE.UU.)'), ('otra', 'Otra entidad acreditadora'), ('no_acreditado', 'No acreditado')], default='no_acreditado', max_length=20, verbose_name='Entidad acreditadora'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='estado_aprobacion',
            field=models.CharField(choices=[('aprobado', 'Aprobado'), ('en_evaluacion', 'En evaluación'), ('suspendido', 'Suspendido'), ('no_aplica', 'No aplica')], default='no_aplica', max_length=20, verbose_name='Estado de aprobación'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='fecha_ultima_evaluacion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha última evaluación del proveedor'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='laboratorio_acreditado',
            field=models.BooleanField(default=False, help_text='Aplica principalmente a proveedores de calibración. Marcar si el proveedor cuenta con acreditación vigente.', verbose_name='¿Laboratorio acreditado?'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='numero_acreditacion',
            field=models.CharField(blank=True, default='', help_text='Ej: ONAC-L-0123', max_length=100, verbose_name='Número de acreditación'),
        ),
    ]
