# Generated by Django 5.2.12 on 2026-07-30 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_empresa_modulo_prestamos_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='empresa_matriz',
            field=models.ForeignKey(blank=True, help_text='Si esta empresa es una sede, selecciona aquí la empresa matriz (holding) a la que pertenece.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sedes', to='core.empresa', verbose_name='Empresa Matriz'),
        ),
    ]
