# Generated by Django 5.2.12 on 2026-09-14 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_agregar_empresa_matriz'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferenciaEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_interno_anterior', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo_interno_nuevo', models.CharField(blank=True, help_text='Solo se llena si el código chocaba con uno existente en la sede destino.', max_length=100, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('empresa_destino', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias_entrada', to='core.empresa', verbose_name='Empresa de Destino')),
                ('empresa_origen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias_salida', to='core.empresa', verbose_name='Empresa de Origen')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias', to='core.equipo', verbose_name='Equipo')),
                ('realizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Realizado por')),
            ],
            options={
                'verbose_name': 'Transferencia de Equipo',
                'verbose_name_plural': 'Transferencias de Equipo',
                'ordering': ['-fecha'],
            },
        ),
    ]
